controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Thread;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\EntryForm;
use app\models\Post;
use yii\db\Expression;
use yii\data\ActiveDataProvider;

class SiteController extends Controller
{

    public function actionListThreads()
    {
        $query = Thread::find();
        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 50,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_DESC,
                    'title' => SORT_ASC,
                ]
            ],
        ]);
        return $this->render('threadList', [
            'provider' => $provider,
        ]);
    }

    public function actionCreateThread()
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect(array('/user/login'));
        }
        $newThread = new Thread;
        if ($newThread->load(Yii::$app->request->post())) {
            if ($newThread->validate()) {
                $newThread->timestamp = new Expression('NOW()');
                $newThread->id_user = Yii::$app->user->id;
                //TODO: Make captcha work with serverside validation: https://github.com/yiisoft/yii2/issues/6115
                if ($newThread->save(false)) {
                    $this->setContentCreationDateTime();
                    $this->redirect('/');
                }
                return;
            }
        }
        $secondsBeforeContentCreation = 30;
        return $this->render('createThread', [
            'model' => $newThread,
            'canCreateContent' => $this->canCreateContent($secondsBeforeContentCreation),
            'secondsBeforeContentCreation' => $secondsBeforeContentCreation
        ]);
    }

    public function actionViewThread($id)
    {
        $thread = Thread::find()->where(['id' => $id])->one();
        //Allow view counter to be increased by one user maximum once per 15 minutes.
        $allowedMinutesBeforeViewIncrement = 15;
        $session = Yii::$app->session;
        if (!$session->isActive) $session->open();
        if (!isset($_SESSION['threadViewDateTimes'][$id])) {
            $_SESSION['threadViewDateTimes'][$id] = ['lastTimeVisited' => (new \DateTime())->format('Y-m-d H:i:s')];
            $thread->updateCounters(['viewcount' => 1]);
        } else {
            $now = (new \DateTime());
            $lastVisit = (new \DateTime())->createFromFormat('Y-m-d H:i:s', $_SESSION['threadViewDateTimes'][$id]['lastTimeVisited']);
            $interval = date_diff($now, $lastVisit);
            Yii::info($interval->format('%i'));
            if ($interval->format('%i') > $allowedMinutesBeforeViewIncrement) $thread->updateCounters(['viewcount' => 1]);
            $_SESSION['threadViewDateTimes'][$id] = ['lastTimeVisited' => (new \DateTime())->format('Y-m-d H:i:s')];
        }

        $newPost = new Post;
        if ($newPost->load(Yii::$app->request->post())) {
            if ($newPost->validate()) {
                $newPost->timestamp = new Expression('NOW()');
                $newPost->id_thread = $thread->id;
                $newPost->id_user = Yii::$app->user->id;
                //TODO: Make captcha work with serverside validation: https://github.com/yiisoft/yii2/issues/6115
                if ($newPost->save(false)) {
                    $this->setContentCreationDateTime();
                    $this->redirect("/thread/{$id}");
                } else {
                    Yii::info("");
                }
            }
        }
        $posts = $thread->getPosts()->all();
        $secondsBeforeContentCreation = 30;
        return $this->render('viewThread', [
            'thread' => $thread,
            'posts' => $posts,
            'newPost' => $newPost,
            'canCreateContent' => $this->canCreateContent($secondsBeforeContentCreation),
            'secondsBeforeContentCreation' => $secondsBeforeContentCreation
        ]);
    }

    public function setContentCreationDateTime()
    {
        $_SESSION['lastContentCreationDateTime'] = (new \DateTime())->format('Y-m-d H:i:s');
    }

    public function canCreateContent($secondsBeforeContentCreation)
    {
        $session = Yii::$app->session;
        if (!$session->isActive) $session->open();
        if (!isset($_SESSION['lastContentCreationDateTime'])) {
            $_SESSION['lastContentCreationDateTime'] = '';
            return true;
        } else {
            if($_SESSION['lastContentCreationDateTime'] == '') return true;
            $now = (new \DateTime());
            $lastContentCreationDateTime = (new \DateTime())->createFromFormat('Y-m-d H:i:s', $_SESSION['lastContentCreationDateTime']);
            $interval = date_diff($now, $lastContentCreationDateTime);
            Yii::info($interval->format('%s'));
            if ($interval->format('%s') > $secondsBeforeContentCreation) return true;
        }
    }

    public function actionThreadUpVote($threadId)
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect(array('/user/login'));
        }
        $thread = Thread::find()->where(['id' => $threadId])->one();
        $thread->vote(Yii::$app->user->id, 1);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionThreadDownVote($threadId)
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect(array('/user/login'));
        }
        $thread = Thread::find()->where(['id' => $threadId])->one();
        $thread->vote(Yii::$app->user->id, -1);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionPostUpVote($postId)
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect(array('/user/login'));
        }
        $post = Post::find()->where(['id' => $postId])->one();
        $post->vote(Yii::$app->user->id, 1);
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionPostDownVote($postId)
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect(array('/user/login'));
        }
        $post = Post::find()->where(['id' => $postId])->one();
        $post->vote(Yii::$app->user->id, -1);
        return $this->redirect(Yii::$app->request->referrer);
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
//            'captcha' => [
//                'class' => 'app\models\captcha\CaptchaAction',
//                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
//            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
            ],
        ];
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/site/createThread.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\captcha\Captcha;

/* @var $this yii\web\View */
/* @var $model app\models\Thread */
/* @var $form ActiveForm */
?>

<div class="createThread">
    <?php if (!$canCreateContent): ?>
        <div class="alert alert-danger" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            Sorry, the creation time between new content must be greater
            than <?= Html::encode($secondsBeforeContentCreation) ?> seconds. Please try later.
        </div>
        <?= Html::a('Return to forum index', [Url::to(['/'])], [
        'class' => 'btn btn-primary']) ?>
        <?php else: ?>
        <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, 'title') ?>
        <?= $form->field($model, 'content')->textarea() ?>
        <?= $form->field($model, 'captcha')->widget(\yii\captcha\Captcha::className()) ?>
        <div class="form-group">
            <?= Html::submitButton('Create new Thread', ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Cancel', [Url::to(['/'])], [
                'class' => 'btn btn-danger grid-button'
            ]) ?>
        </div>
        <?php ActiveForm::end(); ?>
    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/threadList.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use fedemotta\datatables\DataTables;
?>

<h1>Welcome to the Yii2 Forum!</h1>

<!--Only registered users can create a new Thread-->
<?php
if (!Yii::$app->user->isGuest) {
    echo Html::a('Create new Thread', [Url::to(['thread/create'])], [
        'class' => 'btn btn-primary grid-button',
        'id' => 'create-thread-btn',
        'style' => 'margin-bottom:10px'
    ]);
}
?>

<div class="well well-sm">
    <?= DataTables::widget([
        'dataProvider' => $provider,
        //    'filterModel' => $threads,
        'clientOptions' => [
            'lengthChange' => false,
            'paging' => false,
            'order' => [2, 'desc']
        ],
        'columns' => [
            [
                'label' => 'Title',
                'format' => 'raw',
                'value' => function ($thread) {
                    return Html::a("{$thread->title}", Url::to([
                        'site/view-thread',
                        'id' => $thread->id,
                    ]));
                        //['onclick' => "incrementThreadViewCount($thread->id)"]);
                },
            ],
            'authorname',
            'timestamp',
            [
                'label' => 'Views',
                'format' => 'raw',
                'value' => function ($thread) {
                    $html = Html::encode($thread->viewcount);
                    return $html;
                },
            ],
            [
                'label' => 'Votes',
                'format' => 'raw',
                'value' => function ($thread) {
                    $html = Html::encode($thread->votingcount);
                    return $html;
                },
            ],
            [
                'label' => 'Replies',
                'format' => 'raw',
                'value' => function ($thread) {
                    $html = Html::encode($thread->replies);
                    return $html;
                },
            ],
        ],
    ]); ?>
</div>

<script>
    function incrementThreadViewCount(threadId) {
        $.ajax({
            url: '<?php echo Yii::$app->request->baseUrl . 'thread/incrementviewcount/'?>' + threadId,
            data: {threadId: threadId},
            type: "GET",
            success: function () {
            },
            error: function () {
            }
        });
    }
</script>

views/site/viewThread.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\captcha\Captcha;

?>

<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
<div class="container">
    <?= Html::a('Return to Forum index', [Url::to(['/'])], [
        'class' => 'btn btn-primary grid-button',
        'style' => 'margin-bottom:10px'
    ]) ?>
    <div class="well well-sm" style="background: rgba(255,225,175,0.09)">
        <div class="media">
            <div class="media-body">
                <h3 class="media-heading">Title: <?= Html::encode($thread->title) ?></h3>
                <p class="text-right"><i class="glyphicon glyphicon-user"></i>
                    By <?= Html::encode($thread->authorname) ?>
                </p>
                <p><?= Html::encode($thread->content) ?></p>
                <ul class="list-inline list-unstyled">
                    <li>
                        <span><i class="glyphicon glyphicon-calendar"></i> <?= Html::encode($thread->timestamp) ?></span>
                    </li>
                    <li>|</li>
                    <span><i class="glyphicon glyphicon-eye-open"></i> Views: <?= Html::encode($thread->viewcount) ?> </span>
                    <li>|</li>
                    <span><i class="glyphicon glyphicon-heart-empty"></i> Votes: <?= Html::encode($thread->votingcount) ?> </span>
                    <?php if (!Yii::$app->user->isGuest): ?>
                        <li>|</li>
                        <span><?= Html::a('UpVote', [Url::to(['site/thread-up-vote', 'threadId' => $thread->id])], [
                                'class' => 'btn btn-primary grid-button btn-xs'
                            ]) ?>
                            <?= Html::a('DownVote', [Url::to(['site/thread-down-vote', 'threadId' => $thread->id])], [
                                'class' => 'btn btn-primary grid-button btn-xs'
                            ]) ?></span>
                        <li>|</li>
                        <span> Your current vote: <?= Html::encode($thread->getUserVote(Yii::$app->user->id)) ?> </span>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>


    <?php if (count($posts) === 0): ?>
        <h4>No Replies yet.</h4>
    <?php else: ?>
        <h4>Replies:</h4>
    <?php endif; ?>


    <?php foreach ($posts as $post): ?>
        <div class="well well-sm" style="background: rgba(216,132,186,0.09)">
            <p class="text-right"><i class="glyphicon glyphicon-user"></i>
                By <?= Html::encode($post->authorname) ?>
            </p>
            <p><?= Html::encode($post->content) ?></p>
            <ul class="list-inline list-unstyled">
                <li>
                    <span><i class="glyphicon glyphicon-calendar"></i> <?= Html::encode($post->timestamp) ?></span>
                </li>
                <li>|</li>
                <span><i class="glyphicon glyphicon-heart-empty"></i> Votes: <?= Html::encode($post->votingcount) ?> </span>
                <?php if (!Yii::$app->user->isGuest): ?>
                    <li>|</li>
                    <span><?= Html::a('UpVote', [Url::to(['site/post-up-vote', 'postId' => $post->id])], [
                            'class' => 'btn btn-primary grid-button btn-xs',
                            'style' => ''
                        ]) ?>
                        <?= Html::a('DownVote', [Url::to(['site/post-down-vote', 'postId' => $post->id])], [
                            'class' => 'btn btn-primary grid-button btn-xs',
                            'style' => ''
                        ]) ?></span>
                    <li>|</li>
                    <span> Your current vote: <?= Html::encode($post->getUserVote(Yii::$app->user->id)) ?> </span>
                <?php endif; ?>
            </ul>
        </div>
    <?php endforeach; ?>

    <!--Only registered users can reply in a Thread-->
    <?php if (!Yii::$app->user->isGuest): ?>
        <?php if (!$canCreateContent): ?>
            <div class="alert alert-info" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                You must wait <?= Html::encode($secondsBeforeContentCreation) ?> seconds before creating new content.
            </div>
        <?php else: ?>
            <div class="viewThread">
                <?php $form = ActiveForm::begin(); ?>
                <?= $form->field($newPost, 'content')->textarea()->label('Reply') ?>
                <?= $form->field($newPost, 'captcha')->widget(\yii\captcha\Captcha::className()) ?>
                <div class="form-group">
                    <?= Html::submitButton('Reply', ['class' => 'btn btn-primary']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

</div>